/* Справочник товаров, команда и стартовые данные. */

var SEED_VERSION = 17;

var SEED_RETIRE = {
  "returns": ["r-2026-08-15", "r-2026-07-21"]   // августовские 17,25 € вошли в эту запись, отдельной строкой не нужны
};

var TEAM_SEED = [
  {
    "id": "1285269855",
    "name": "Миша",
    "role": "admin"
  },
  {
    "id": "587696431",
    "name": "—",
    "role": "admin"
  },
  {
    "id": "613401293",
    "name": "Элина",
    "role": "admin"
  },
  {
    "id": "1615696701",
    "name": "Маша",
    "role": "admin"
  },
  {
    "id": "576731189",
    "name": "Даша",
    "role": "admin"
  },
  {
    "id": "450027563",
    "name": "Рита",
    "role": "admin"
  },
  {
    "id": "383734034",
    "name": "Женя",
    "role": "admin"
  },
  {
    "id": "768906473",
    "name": "Света",
    "role": "admin"
  },
  {
    "id": "1473311875",
    "name": "Алмаз",
    "role": "admin"
  }
];

var RETURNS_SEED = [
  {
    "id": "r-start-2026-05-20",
    "date": "2026-05-20T12:00:00.000Z",
    "by": "Миша",
    "amount": 39.6,
    "units": 264,
    "toTill": false,
    "note": "Сдачи с 20.05 по 26.07, до начала периода. Одной записью."
  },
  {
    "id": "r-2026-09-19",
    "date": "2026-09-19T12:00:00.000Z",
    "by": "Миша",
    "amount": 30.8,
    "units": 205,
    "toTill": true,
    "note": "Сдачи с 26.07 по 21.09, включая забытый августовский платёж 17,25 €. Деньги легли в кассу."
  }
];

var SEED = {
  "counts": {
    "c-2026-07-22": {
      "by": "чек Metro",
      "card": 0,
      "cash": 0,
      "date": "2026-07-22T13:21:00.000Z",
      "initial": true,
      "note": "Опорная точка: остаток сразу после закупки в Metro. Позиции без закупки взяты по текущему подсчёту — они стояли там же.",
      "source": "Metro faktúra 0/0/2003/026117 · 190,33 €",
      "stock": {
        "aro05": 120,
        "aro15": 12,
        "aro15gas": 2,
        "chips_sk": 0,
        "chivas12": 1,
        "chrumky": 1,
        "citronka1": 1,
        "citronka15": 1,
        "coffee": 72,
        "coffee_plombir": 6,
        "cola033": 24,
        "cola2": 5,
        "colazero2": 1,
        "dimple": 1,
        "gin_beefeater": 1,
        "hell250": 48,
        "hrusk_spis": 1,
        "jack07": 1,
        "jack_silver": 1,
        "juice_grape": 2,
        "juice_orange": 1,
        "kofola2": 6,
        "kozel05": 0,
        "maccoffee": 11,
        "marhul_spis": 1,
        "marhul_tri": 1,
        "pelle033": 12,
        "popcorn": 4,
        "pryaniki": 1,
        "red_label": 1,
        "redbull250": 0,
        "slivki": 1,
        "staro05": 7,
        "staro15": 12,
        "syrove_koule": 1,
        "tea_forest": 1,
        "tea_menta": 1,
        "tea_pigi": 1,
        "tea_zen": 1,
        "tequila_gold": 1,
        "tequila_repo": 1,
        "tonic15": 4,
        "wine_frankovka": 1,
        "wine_mat_mt": 1,
        "wine_mat_polo": 2,
        "wine_mat_suche": 4,
        "wine_querceto": 3,
        "wine_vitis_red": 1,
        "wine_vitis_white": 1,
        "zbnealko": 38,
        "zbtmave": 12
      }
    },
    "c-2026-09-20": {
      "by": "Миша",
      "card": 141.15,
      "cash": 0,
      "date": "2026-09-20T15:00:00.000Z",
      "note": "Деньги: 141,15 € пришло за период 22.07–20.09. Полный список позиций сверен 21.09.",
      "stock": {
        "aro05": 39,
        "aro15": 6,
        "aro15gas": 2,
        "chips_sk": 0,
        "chivas12": 1,
        "chrumky": 1,
        "citronka1": 1,
        "citronka15": 1,
        "coffee": 72,
        "coffee_plombir": 6,
        "cola033": 0,
        "cola2": 5,
        "colazero2": 1,
        "dimple": 1,
        "gin_beefeater": 1,
        "hell250": 4,
        "hrusk_spis": 1,
        "jack07": 1,
        "jack_silver": 1,
        "juice_grape": 2,
        "juice_orange": 1,
        "kofola2": 2,
        "kozel05": 21,
        "maccoffee": 11,
        "marhul_spis": 1,
        "marhul_tri": 1,
        "pelle033": 0,
        "popcorn": 4,
        "pryaniki": 1,
        "red_label": 1,
        "redbull250": 0,
        "slivki": 1,
        "staro05": 7,
        "staro15": 12,
        "syrove_koule": 1,
        "tea_forest": 1,
        "tea_menta": 1,
        "tea_pigi": 1,
        "tea_zen": 1,
        "tequila_gold": 1,
        "tequila_repo": 1,
        "tonic15": 4,
        "wine_frankovka": 1,
        "wine_mat_mt": 1,
        "wine_mat_polo": 2,
        "wine_mat_suche": 4,
        "wine_querceto": 3,
        "wine_vitis_red": 1,
        "wine_vitis_white": 1,
        "zbnealko": 0,
        "zbtmave": 0
      }
    }
  },
  "meta": {
    "costNote": "cost — цена с НДС без залога. dep — залог за тару, возвратный.",
    "deposit": 0.15,
    "vat": {
      "drinks": 0.23,
      "water": 0.19
    }
  },
  "products": {
    "aro05": {
      "cat": "water",
      "color": "#4FA3D9",
      "cost": 0.24,
      "dep": 0.15,
      "min": 12,
      "name": "Вода Aro",
      "note": "Metro 22.07: 0,20 € без НДС после акции, +19% = 0,24 €. Залог 0,15 € возвращается.",
      "order": 10,
      "pack": 12,
      "phaseout": false,
      "shape": "water",
      "vol": "0,5 л · негаз."
    },
    "aro15": {
      "cat": "water",
      "color": "#3B8BC4",
      "cost": 0.32,
      "dep": 0.15,
      "min": 12,
      "name": "Вода Aro",
      "note": "Metro 22.07: 0,27 € без НДС, +19% = 0,32 €. Залог 0,15 € возвращается.",
      "order": 11,
      "pack": 6,
      "phaseout": false,
      "shape": "water",
      "vol": "1,5 л · негаз."
    },
    "aro15gas": {
      "cat": "shared",
      "color": "#7FB3D5",
      "cost": 0.32,
      "dep": 0.15,
      "min": 2,
      "name": "Вода Aro",
      "note": "Газированную не докупаем — это не питьевая вода для команды.",
      "order": 29,
      "pack": 6,
      "phaseout": true,
      "shape": "water",
      "vol": "1,5 л · газ."
    },
    "chips_sk": {
      "cat": "snack",
      "color": "#C0392B",
      "cost": 1.23,
      "dep": 0.0,
      "min": 2,
      "name": "Чипсы Slovakia",
      "note": "Новая позиция, заведена с нуля. Минимум 2 шт — сколько уходит, увидим после следующего подсчёта.",
      "order": 14,
      "pack": null,
      "phaseout": false,
      "shape": "carton",
      "vol": "малая пачка"
    },
    "chivas12": {
      "cat": "shared",
      "color": "#1F4E3D",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Chivas Regal 12",
      "order": 59,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "chrumky": {
      "cat": "snack",
      "color": "#F0C24B",
      "cost": 0.47,
      "dep": 0.0,
      "min": 2,
      "name": "Chrumky",
      "order": 13,
      "pack": null,
      "phaseout": false,
      "shape": "carton",
      "vol": "пачка"
    },
    "citronka1": {
      "cat": "shared",
      "color": "#F1C40F",
      "cost": 1.34,
      "dep": 0.0,
      "min": 1,
      "name": "Citrónka",
      "note": "Metro 30.07: 1,28 € без НДС, ставка 5% → 1,34 € с НДС.",
      "order": 33,
      "pack": null,
      "phaseout": true,
      "shape": "pet",
      "vol": "1 л · 40%"
    },
    "citronka15": {
      "cap": "#F4D03F",
      "cat": "shared",
      "color": "#F4D03F",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Citrónka",
      "order": 32,
      "pack": null,
      "phaseout": true,
      "shape": "pet",
      "vol": "1,5 л"
    },
    "coffee": {
      "cat": "sale",
      "color": "#6B4226",
      "cost": null,
      "dep": 0.0,
      "min": 15,
      "name": "Кофе-капсула",
      "note": "Впиши цену капсулы с НДС — посчитается маржа.",
      "order": 6,
      "pack": null,
      "phaseout": false,
      "shape": "capsule",
      "vol": "1 шт"
    },
    "coffee_plombir": {
      "cat": "shared",
      "color": "#D9C3A0",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Кофейный напиток «Пломбир»",
      "order": 66,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "стики"
    },
    "cola033": {
      "cat": "sale",
      "color": "#D71920",
      "cost": 0.89,
      "dep": 0.15,
      "min": 6,
      "name": "Coca-Cola / Zero",
      "note": "Metro 22.07: 0,59 € без НДС, +23% = 0,73 €. Обычная и Zero по одной цене.",
      "order": 4,
      "pack": 24,
      "phaseout": false,
      "shape": "can",
      "vol": "0,33 л · банка"
    },
    "cola2": {
      "cap": "#D71920",
      "cat": "shared",
      "color": "#D71920",
      "cost": 2.14,
      "dep": 0.15,
      "min": 1,
      "name": "Coca-Cola",
      "note": "Metro 22.07: 1,74 € без НДС, +23% = 2,14 €.",
      "order": 20,
      "pack": 6,
      "phaseout": true,
      "shape": "pet",
      "vol": "2 л"
    },
    "colazero2": {
      "cap": "#D71920",
      "cat": "shared",
      "color": "#1A1A1A",
      "cost": 2.14,
      "dep": 0.15,
      "min": 1,
      "name": "Coca-Cola Zero",
      "note": "Цена принята как у обычной 2 л — в чеке 22.07 её не было.",
      "order": 21,
      "pack": 6,
      "phaseout": true,
      "shape": "pet",
      "vol": "2 л"
    },
    "dimple": {
      "cat": "shared",
      "color": "#B8860B",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Dimple Golden Selection",
      "order": 60,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "gin_beefeater": {
      "cat": "shared",
      "color": "#2E5E4E",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Gin Beefeater",
      "order": 53,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "hell250": {
      "cat": "sale",
      "color": "#1E1E24",
      "cost": 0.65,
      "dep": 0.15,
      "min": 6,
      "name": "Hell Energy",
      "note": "Tesco 17.08: 1,89 € за 4 шт с НДС = 0,47 €/шт. В Metro было дороже — 0,73 € с НДС.",
      "order": 5,
      "pack": 24,
      "phaseout": false,
      "shape": "can",
      "vol": "0,25 л · банка"
    },
    "hrusk_spis": {
      "cat": "shared",
      "color": "#CFCFAF",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Hruškovica Spišská",
      "order": 51,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "jack07": {
      "cat": "shared",
      "color": "#1A1A1A",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Jack Daniel's",
      "order": 57,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "jack_silver": {
      "cat": "shared",
      "color": "#4A4A4A",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Jack Daniel's Silver Select",
      "order": 58,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "juice_grape": {
      "cat": "shared",
      "color": "#E4717A",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Сок Happy Day",
      "order": 30,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "розовый грейпфрут · 1 л"
    },
    "juice_orange": {
      "cat": "shared",
      "color": "#F39C12",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Сок Pfanner",
      "order": 31,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "апельсин · 2 л"
    },
    "kofola2": {
      "cap": "#C8102E",
      "cat": "shared",
      "color": "#4A2A17",
      "cost": 1.75,
      "dep": 0.15,
      "min": 1,
      "name": "Kofola",
      "note": "Metro 22.07: 1,43 € без НДС, +23% = 1,75 €. Была акция «Kofola за 1 €».",
      "order": 22,
      "pack": 6,
      "phaseout": true,
      "shape": "pet",
      "vol": "2 л"
    },
    "kozel05": {
      "cat": "sale",
      "color": "#8E2B2F",
      "cost": 0.58,
      "dep": 0.15,
      "min": 6,
      "name": "Kozel",
      "note": "Metro 30.07: 0,51 € без НДС минус акция = 0,47 €, +23% = 0,58 €. Залог 0,15 € отдельно.",
      "order": 1,
      "pack": 20,
      "phaseout": false,
      "shape": "can",
      "vol": "0,5 л · банка · 4,2%"
    },
    "maccoffee": {
      "cat": "shared",
      "color": "#8B5A2B",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "MacCoffee",
      "order": 65,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "стики"
    },
    "marhul_spis": {
      "cat": "shared",
      "color": "#D9A441",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Marhuľovica Spišská",
      "order": 50,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "marhul_tri": {
      "cat": "shared",
      "color": "#D9A441",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Marhuľovica Tri stromy",
      "order": 52,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л · открыта"
    },
    "pelle033": {
      "cat": "sale",
      "color": "#E8552D",
      "cost": 0.99,
      "dep": 0.15,
      "min": 6,
      "name": "San Pellegrino",
      "note": "Metro 22.07: 0,92 € без НДС, +23% = 1,13 €. В чеке «MAND.» — вкус Clementina.",
      "order": 7,
      "pack": 6,
      "phaseout": false,
      "shape": "can",
      "vol": "0,33 л · банка · мандарин"
    },
    "popcorn": {
      "cat": "snack",
      "color": "#E8A33D",
      "cost": null,
      "dep": 0.0,
      "min": 2,
      "name": "Popcorn Chio",
      "order": 12,
      "pack": 1,
      "phaseout": false,
      "shape": "carton",
      "vol": "пачка · соль, масло, сыр"
    },
    "pryaniki": {
      "cat": "snack",
      "color": "#A9714B",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Медовые пряники",
      "order": 17,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "пачка"
    },
    "red_label": {
      "cat": "shared",
      "color": "#8B1A1A",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Johnnie Walker Red Label",
      "order": 56,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л · половина"
    },
    "redbull250": {
      "cat": "sale",
      "color": "#1B3A6B",
      "cost": 1.29,
      "dep": 0.15,
      "min": 6,
      "name": "Red Bull",
      "note": "Новая позиция. Впиши цену закупки с НДС.",
      "order": 5.5,
      "pack": 24,
      "phaseout": false,
      "shape": "can",
      "vol": "0,25 л · банка"
    },
    "slivki": {
      "cap": "#1F3C88",
      "cat": "shared",
      "color": "#1F3C88",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Сливки Maresi",
      "note": "Maresi. Плюс 2 открытые на 20.09 — не считаются.",
      "order": 25,
      "pack": null,
      "phaseout": true,
      "shape": "pet",
      "vol": "Maresi Original · закрытые"
    },
    "staro05": {
      "cat": "sale",
      "color": "#B8322E",
      "cost": 0.6,
      "dep": 0.15,
      "min": 6,
      "name": "Staropramen",
      "note": "Metro 22.07: 0,49 € без НДС, +23% = 0,60 €.",
      "order": 2,
      "pack": 20,
      "phaseout": false,
      "shape": "can",
      "vol": "0,5 л · банка · 4%"
    },
    "staro15": {
      "cap": "#D9A441",
      "cat": "shared",
      "color": "#B8322E",
      "cost": null,
      "dep": 0.15,
      "min": 2,
      "name": "Staropramen",
      "order": 24,
      "pack": 6,
      "phaseout": true,
      "shape": "pet",
      "vol": "1,5 л · ПЭТ · 4%"
    },
    "syrove_koule": {
      "cat": "snack",
      "color": "#E8C04D",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Syrové koule",
      "order": 16,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "пачка"
    },
    "tea_forest": {
      "cat": "shared",
      "color": "#7D3C98",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Teekanne forest fruit",
      "order": 64,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "открытая пачка"
    },
    "tea_menta": {
      "cat": "shared",
      "color": "#4E9A51",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Teekanne mäta",
      "order": 63,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "открытая пачка"
    },
    "tea_pigi": {
      "cat": "shared",
      "color": "#6B4226",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Чай чёрный Pigi",
      "order": 62,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "пачка"
    },
    "tea_zen": {
      "cat": "shared",
      "color": "#4E9A51",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Чай зелёный Zen Chai",
      "order": 61,
      "pack": null,
      "phaseout": true,
      "shape": "carton",
      "vol": "пачка"
    },
    "tequila_gold": {
      "cat": "shared",
      "color": "#C9A227",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Tequila Gold",
      "order": 54,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "осталось ~3 шота"
    },
    "tequila_repo": {
      "cat": "shared",
      "color": "#B8860B",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Tequila Reposado",
      "order": 55,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,7 л"
    },
    "tonic15": {
      "cap": "#E8B400",
      "cat": "shared",
      "color": "#6FA898",
      "cost": null,
      "dep": 0.15,
      "min": 1,
      "name": "Kinley Tonic",
      "order": 23,
      "pack": 6,
      "phaseout": true,
      "shape": "pet",
      "vol": "1,5 л"
    },
    "wine_frankovka": {
      "cat": "shared",
      "color": "#7B1E2B",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Frankovka modrá",
      "order": 44,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,75 л · červené suché"
    },
    "wine_mat_mt": {
      "cat": "shared",
      "color": "#C9B037",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Matyšák Müller Thurgau",
      "order": 42,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,75 л · biele suché"
    },
    "wine_mat_polo": {
      "cat": "shared",
      "color": "#D4AF6A",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Matyšák Müller & Irsai",
      "order": 41,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,75 л · biele polosuché"
    },
    "wine_mat_suche": {
      "cat": "shared",
      "color": "#C9B037",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Matyšák biele suché",
      "order": 40,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,75 л"
    },
    "wine_querceto": {
      "cat": "shared",
      "color": "#6E2233",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Querceto Chianti",
      "order": 43,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "0,75 л · červené suché"
    },
    "wine_vitis_red": {
      "cat": "shared",
      "color": "#6E2233",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Vitis Zámocké",
      "order": 45,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "1 л · červené suché"
    },
    "wine_vitis_white": {
      "cat": "shared",
      "color": "#C9B037",
      "cost": null,
      "dep": 0.0,
      "min": 1,
      "name": "Vitis Zámocké",
      "order": 46,
      "pack": null,
      "phaseout": true,
      "shape": "bottle",
      "vol": "1 л · biele suché"
    },
    "zbnealko": {
      "cat": "sale",
      "color": "#2E7D4F",
      "cost": 0.79,
      "dep": 0.15,
      "min": 6,
      "name": "Zlatý Bažant 0,0%",
      "note": "Metro 22.07: 0,64 € без НДС, +23% = 0,79 €. Birell 0,0% считаем этой же позицией.",
      "order": 3,
      "pack": 6,
      "phaseout": false,
      "shape": "can",
      "vol": "0,5 л · банка · nealko, разные вкусы"
    },
    "zbtmave": {
      "cat": "sale",
      "color": "#5C3317",
      "cost": 1.26,
      "dep": 0.15,
      "min": 6,
      "name": "Zlatý Bažant tmavé",
      "note": "Metro 22.07: 0,79 € без НДС, +23% = 0,97 €.",
      "order": 2.5,
      "pack": 6,
      "phaseout": false,
      "shape": "can",
      "vol": "0,5 л · банка · тёмное"
    }
  },
  "purchases": {
    "p-2026-07-30": {
      "by": "Миша",
      "date": "2026-07-30T14:45:00.000Z",
      "items": {
        "kozel05": 48
      },
      "source": "Metro 30.07, фактура 0/0(025)0056/012713 · 54,18 €. В чеке только Kozel наш.",
      "total": 54.18
    },
    "p-2026-08-17": {
      "by": "Миша",
      "date": "2026-08-17T12:10:00.000Z",
      "items": {
        "hell250": 72
      },
      "source": "Tesco Ružinov 17.08 · 18 × 4 шт по 1,89 € + залог 10,80 €",
      "total": 44.82
    }
  },
  "returns": {
    "r-start-2026-05-20": {
      "date": "2026-05-20T12:00:00.000Z",
      "by": "Миша",
      "amount": 39.6,
      "units": 264,
      "toTill": false,
      "note": "Сдачи с 20.05 по 26.07, до начала периода. Одной записью."
    },
    "r-2026-09-19": {
      "date": "2026-09-19T12:00:00.000Z",
      "by": "Миша",
      "amount": 30.8,
      "units": 205,
      "toTill": true,
      "note": "Сдачи с 26.07 по 21.09, включая забытый августовский платёж 17,25 €. Деньги легли в кассу."
    }
  }
};
